# Generated by Django 3.1.7 on 2021-03-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210316_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='destination',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
