# Generated by Django 3.1.7 on 2021-03-18 14:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210318_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_plan_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='base',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
